"""add status enum

Revision ID: 07102770d3f4
Revises: fc31a0b77bc0
Create Date: 2026-02-24 17:43:41.947199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07102770d3f4'
down_revision: Union[str, Sequence[str], None] = 'fc31a0b77bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('status', sa.Enum('pending', 'ongoing', 'done', name='statustype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'status')
    # ### end Alembic commands ###
